eureka:
  instance:
    prefer-ip-address: true
  client:
    serviceUrl:
      defaultZone: http://192.168.1.3:8761/eureka/

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://encare.c3i6z4ygf2dg.ap-southeast-1.rds.amazonaws.com:3306/encare
    username: root
    password: EnCare123456!!
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect

application:
  security:
    secret-key: encare

#spring:
#  datasource:
#    driver-class-name: com.mysql.cj.jdbc.Driver
#    url: jdbc:mysql://sql6.freesqldatabase.com:3306/sql6510273
#    username: sql6510273
#    password: a7cMJNLpXt

# spring:
#   datasource:
#     driver-class-name: com.mysql.cj.jdbc.Driver
#     url: jdbc:mysql://localhost:3306/encare
#     username: root
#     password: 123456789